{
 "title": "Transmission exporter",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Global download speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transmission_download_bytes_per_second",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All time downloaded",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transmission_downloaded_bytes_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Global ratio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transmission_uploaded_bytes_total / transmission_downloaded_bytes_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Torrent count by status",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (transmission_torrents)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total sessions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "transmission_sessions_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Global upload speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transmission_upload_bytes_per_second",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All time uploaded",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transmission_uploaded_bytes_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time active",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transmission_seconds_active_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmission version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "transmission_version_info == 1", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Global download / upload speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "transmission_download_bytes_per_second",
     "legendFormat": "download speed"
    },
    {
     "expr": "transmission_upload_bytes_per_second",
     "legendFormat": "upload speed"
    }
   ]
  },
  {
   "title": "Download speed by torrent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "transmission_torrent_download_bytes_per_second * on (hash)\ngroup_left(name) transmission_torrent_info",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Upload speed by torrent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "transmission_torrent_upload_bytes_per_second * on (hash)\ngroup_left(name) transmission_torrent_info",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Torrents",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    { "expr": "transmission_torrent_info", "legendFormat": "__auto" },
    {
     "expr": "sum by (hash) (transmission_torrent_download_bytes_per_second)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (hash) (transmission_torrent_upload_bytes_per_second)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (hash) (transmission_torrent_peers_getting_from_us)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (hash) (transmission_torrent_peers_sending_to_us)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (hash) (transmission_torrent_size_when_done_bytes)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(transmission_torrent_size_when_done_bytes - transmission_torrent_left_until_done_bytes) / transmission_torrent_size_when_done_bytes",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (hash) (transmission_torrent_status)",
     "legendFormat": "__auto"
    },
    {
     "expr": "transmission_torrent_uploaded_bytes_total / transmission_torrent_downloaded_bytes_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}